### ISSUE TITLE
Support policy subset loading

### ISSUE THREAD

**Issue by hsluoyz** [apache/casbin-3rd-party-casbin-pg-adapter#1]
Refer to: https://github.com/cychiuae/casbin-pg-adapter/issues/3

**Comment by hsluoyz** [comment]
@fgblomqvist can you also move your other issues here to this repo? So we can better link the PR to close the issue :)

**Comment by fgblomqvist** [comment]
Has it been concluded that the maintainer from the other repo is unreachable?

**Comment by hsluoyz** [comment]
@fgblomqvist not yet. I can't find any other way to contact the owner. As it seems that the owner was not active at GitHub for weeks, we forked here for a quicker issue resolving. We can also suspend the work here to wait for the owner's response. Plz open issues here when you think it's ready.
